### ISSUE TITLE
isDashlaneAppExtensionAvailable ?

### ISSUE THREAD

**Issue by Droppix** [Dashlane/Dashlane-iOS-Extension#3]
Hi

I try to integrate Dashlane in my app, but`if ([DashlaneExtensionRequestHelper isDashlaneAppExtensionAvailable]) {}` don't work.

Yet "Dashlane" is well installed on my iphone. (1password work).

Thanks for your help

**Comment by irew** [comment]
Could you try to white-list `dashlane-ext` as per the instructions found here:

https://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/

**Comment by Droppix** [comment]
I try, but don't work 
BOOL test = [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"dashlane-ext://"]];

--> test = NO

Tested on iPhone X (iOS 11.2.1)
